# The following three options specify
# a madlibs-style description of yourself.
# I ____________  at ____________________.
# I like ________________________________.
# No need for periods, we'll add them :)

I: build Health Apps
at: Impact Lab, ASU.
I like: to try new technologies, read change logs, hack my brain
